### PR TITLE
Add filter function to process to get rid of carriage characters

### PR DESCRIPTION
**Pull request by Davidbrcz**
git's progress uses return carriage characters for displaying the progress. 
They were (at least on my machine) not handled and displayed as it, hence prompting a huge popup after each fetch.

This PR fixes it by adding a filter function (that is taken from SO).

### CODE REVIEW

**Comment by andrmuel** [comment]
I would like to understand the problem a bit better before adding a filter by default. Can you tell me if you have any special git options set to cause this? Which version of git are you using?

Depending on how many users are affected, I might rather just add this as an option (disabled by default).

Alternatively (without further investigation or if your setup is quite non-standard) I'm happy to just add a generic option to set a process filter and you could add the filter in your configuration.

**Comment by Davidbrcz** [comment]
On my machine (Ubuntu 18.04, git version 2.17.1, GNU Emacs 26.1 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.22.30) of 2018-05-29), the messages from git auto fetch look like this. 
git autofetch.

With my filter fix, they look like this
autofetchOK

**Comment by Davidbrcz** [comment]
On my machine (Ubuntu 18.04, git version 2.17.1, GNU Emacs 26.1 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.22.30) of 2018-05-29), the messages from projectile git autofetch look like this. 
git autofetch


With my filter fix, they look like this
autofetchOK

So maybe it's a configuration issue on my side, but it's day and light between the two behaviors.

**Comment by andrmuel** [comment]
You are right, I can reproduce it.
It seems to me the simpler solution would be to add `--no-progress` to `git fetch`. Unless you see any issue with that solution, I'll add it.

**Comment by Davidbrcz** [comment]
What does --no-progress imply ? simply ignoring the progress bar or completely disabling report ? Because the report itself at the end is useful.

**Comment by andrmuel** [comment]
`--no-progress` will turn off the messages about retrieving objects (everything in your screenshot up to and including "Unpacking objects"), but not the results (everything after "From" in your screenshot). I think its a good default, but if you prefer your solution, I can make it configurable and add a generic variable for a configurable process-filter.

**Comment by Davidbrcz** [comment]
Usually, progress bar is useful if something takes long. For code, my guess would be it's not very common and for something that's happens in the background, it's even less useful. So, yes I think that `--no-progress` by default is good. 

But having an option to enable it and a way to set a filter if needed is also a good idea in my opinion =).

**Comment by andrmuel** [comment]
I have added the code in branch `add-no-progress-and-process-filter`. Let me know if that works for you.

**Comment by Davidbrcz** [comment]
I'm by no mean a Elisp expert, but it looks good to me !

**Comment by andrmuel** [comment]
Merged & closing this PR; thanks.

**Pull request closed without merging**
